### ISSUE TITLE
snapshot会不会太占空间了，有配置可以变更吗

### ISSUE THREAD

**Issue by cary1179** [macacajs/macaca-datahub#108]
如题。
每次刷新都会产生一个snapshot，量级太大的话，占据空间也很大。
不太需要的话，有什么办法能禁用吗？
或者，保留的snapshot限制在XX时间范围内或XX数量范围内？

**Comment by xudafeng** [comment]
@cary1179 所说的占据空间大是指哪里？

**Comment by cary1179** [comment]
不好意思，以为是直接读取数据库的。看起来好像是socket实时的。
