### ISSUE TITLE
DataHub start unsuccessfully

### ISSUE THREAD

**Issue by fengxing1** [macacajs/macaca-datahub#109]
DataHub start unsuccessfully: Error: Command failed: /usr/local/lib/node_modules/macaca-datahub/node_modules/sequelize-cli/lib/sequelize db:migrate
ERROR: Please install sqlite3 package manually

Sequelize CLI [Node: 11.4.0, CLI: 4.1.1, ORM: 4.41.2]

Loaded configuration file "database/config.js".

node 版本 v11.4.0

**Comment by zivyangll** [comment]
@fengxing1 reinstall node-modules

**Comment by xudafeng** [comment]
@fengxing1 看日志是sqlite安装失败了，你用cnpm装的？
