### ISSUE TITLE
datahub 可以同步 swagger 信息的变更

### ISSUE THREAD

**Issue by fengsx** [macacajs/macaca-datahub#115]
datahub 可以通过手动或者定时同步某一指定 swagger 信息的变更。

然后之前的可以存档 achieve 到某一个版本中。需要的时候可以切回来。

**Comment by zivyangll** [comment]
> datahub 可以通过手动或者定时同步某一指定 swagger 信息的变更。

同步之后，数据状态无法维护了，比如有个接口数据在 DataHub 改了，在 Swagger 也改了，没法判断以哪个为准

> 然后之前的可以存档 achieve 到某一个版本中。需要的时候可以切回来。

可以通过新建多个 hub 来解决。
