### ISSUE TITLE
datahub server 启动报ERROR: Error reading "database\config.js"

### ISSUE THREAD

**Issue by imjenny** [macacajs/macaca-datahub#120]
datahub server

DataHub start unsuccessfully: Error: Command failed: C:\Users\lee\AppData\Roaming\npm\node_modules\macaca-datahub\node_modules\sequelize-cli\lib\sequelize db:migrate
ERROR: Error reading "database\config.js". Error: TypeError: Path must be a string. Received undefined

Sequelize CLI [Node: 8.11.3, CLI: 4.1.1, ORM: 4.42.0]

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-datahub/commit/4e8e1441f143295a0f7501a933fb18da97b3c6d1
