### ISSUE TITLE
datahub相关请求及界面路径添加/datahub前缀

### ISSUE THREAD

**Issue by likun7981** [macacajs/macaca-datahub#121]
1. 需求
datahub相关请求，路由地址添加`/datahub`前缀
2. 最终实现效果
项目启动地址为`http://localhost:8888`  
希望通过在本项目启动地址加上`http://localhost:8888/datahub` 直接访问配置界面，这样每一个datahub 跟着项目走，而不需要一个单独的地址(端口)去访问datahub配置界面。  
虽然现在通过代理也能实现，因为在`datahub-view`中的跳转地址是写死的，所以需要代理多个path，占用项目多个path`/project`,`/api`,`/data`,`/dashboard`等。这样有可能会导致冲突。如果能加上`/datahub`前缀，这样只需要重写`/datahub`一个path即可。

**Comment by xudafeng** [comment]
@likun7981 mock 服务与你开发页面用的http服务是可以用一个端口的，这样就可以跟着项目走，不侵入项目规定。

比如/project,/api,/data,/dashboard多个path的情况也不是直接重写的，规则：

```javascript
proxy: {
  '^/api': {
    hub: 'datahub_for_api'
  }
}
```

对应的代理逻辑：

```
:8888/api/foo.json => :5678/data/datahub_for_api/api/foo.json
```

确保你的依赖都升级到2

```
macaca-datahub@2
datahub-proxy-middleware@2
```

**Comment by likun7981** [comment]
这个是清楚的，可能我没表达太清楚，我是想配置界面也跟着项目走。不用单独一个链接(端口)去访问配置界面。只需要项目地址+`/datahub`，这样的形式去访问配置界面
