### ISSUE TITLE
[BUG] 升级到2.4出现报错，出现JS ERROR

### ISSUE THREAD

**Issue by ishenli** [macacajs/macaca-datahub#129]
![image](https://user-images.githubusercontent.com/2113885/53245770-a41aa400-36e9-11e9-8d11-ae45dc261a10.png)

**Comment by zivyangll** [comment]
datahub-view 晚上有个小版本升级到 2.3.1，可能是网络问题，datahub-view@2 还没有刷到 2.3.1，可以直接打开 https://unpkg.com/datahub-view@2.3.1/dist/datahub-view.js ，然后再刷新页面。
