### ISSUE TITLE
请求字段描述根本无法编辑

### ISSUE THREAD

**Issue by chenweik** [macacajs/macaca-datahub#130]
编辑接口，接口字段根本无法编辑，双击也实现不了。
![image](https://user-images.githubusercontent.com/8307514/54346681-738eb000-4680-11e9-8529-0ea52b2703ae.png)

为何有的字段可以自动添加进去，有的就不行，而且没有文档描述如何添加字段。
![image](https://user-images.githubusercontent.com/8307514/54347127-4c84ae00-4681-11e9-98e8-e74ccbc67e06.png)

**Comment by zhangyuheng** [comment]
可以在左侧编辑

syntax 的例子参考 https://macacajs.github.io/macaca-datahub/guide/schema-syntax.html

**Comment by chenweik** [comment]
为何不能使用Vue的界面编辑方式，而要重复定义一套Schema语法，本来写接口文档就是一个重复劳动的事情，还要按照Schema语法来重新编辑一个json数据，太过于复杂

**Comment by zivyangll** [comment]
@chenweik 可以先录入接口数据，然后会自动生成 schema 结构的。
