### ISSUE TITLE
Docker镜像没有集成最新功能，和文档描述对照不上，缺失导入Swagger功能

### ISSUE THREAD

**Issue by chenweik** [macacajs/macaca-datahub#131]

**Comment by zivyangll** [comment]
已更新，最新 server 版本：2.4.0

**Comment by mowatermelon** [comment]
通过docker 拉取最新的镜像    版本号 v4.1.4   [实验特性](https://macacajs.github.io/macaca-datahub/zh/guide/experiment.html#%E5%8A%A8%E6%80%81%E6%89%A7%E8%A1%8C-node-js-%E8%84%9A%E6%9C%AC) 提供的功能都没有


<img width="1432" alt="image" src="https://user-images.githubusercontent.com/18508817/174300245-cd83520e-bf83-477e-a49d-8d2629526bc3.png">

**Comment by snapre** [comment]
**实验特性提供的功能需要打开开关才能使用哦**

![image](https://user-images.githubusercontent.com/52845048/175339082-29b1d39e-79ed-473c-b1eb-857cebc09711.png)
![image](https://user-images.githubusercontent.com/52845048/175339509-f7d2d325-e509-4157-818f-74697175bf92.png)
