### ISSUE TITLE
新增场景里的设置响应时间和延迟使用不了

### ISSUE THREAD

**Issue by pandeng0108** [macacajs/macaca-datahub#133]
![image](https://user-images.githubusercontent.com/48948730/54991692-71214400-4ff8-11e9-8cb9-0fb18a76ab59.png)
新增场景里的设置响应时间和延迟使用不了，保存后，再进来就被初始化为空了，使用的是docker部署

**Comment by zivyangll** [comment]
@pandeng0108 macaca-datahub 镜像可以更新下

**Comment by pandeng0108** [comment]
> @pandeng0108 macaca-datahub 镜像可以更新下

您好，现在docker版本多少呢，怎么使用docker命令升级

**Comment by zivyangll** [comment]
@pandeng0108 执行：
```
docker pull macacajs/macaca-datahub
```

启动服务：
```
$ docker run -it -p 9200:9200 -p 9300:9300 macacajs/macaca-datahub
```

查看版本：
访问 http://127.0.0.1:9200/， 主页按钮下面有版本（主要看 server）：
```
server: v2.4.0, view: v2.3.3
```

**Comment by pandeng0108** [comment]
> @pandeng0108 执行：
> 
> ```
> docker pull macacajs/macaca-datahub
> ```
> 启动服务：
> 
> ```
> $ docker run -it -p 9200:9200 -p 9300:9300 macacajs/macaca-datahub
> ```
> 查看版本：
> 访问 [http://127.0.0.1:9200/，](http://127.0.0.1:9200/%EF%BC%8C) 主页按钮下面有版本（主要看 server）：
> 
> ```
> server: v2.4.0, view: v2.3.3
> ```

更新后问题已解决，谢谢
