### ISSUE TITLE
支持自定义备份方式，比如 oss/cdn 等配置

### ISSUE THREAD

**Issue by vagusX** [macacajs/macaca-datahub#134]
当我们将 datahub 部署到 docker 容器后，重启会遇到数据丢失的问题，希望 datahub 可以支持自定义备份方案
* 每次备份时可以支持备份到 oss/cdn
* 或者支持自定义备份方法，由用户自定将需要备份的内容进行备份

**Comment by xudafeng** [comment]
在外围实现比较合适，数据持久化文件默认路径：

```
$HOME/.macaca-datahub
```
