### ISSUE TITLE
Where is macaca datahub store mock data that has been created

### ISSUE THREAD

**Issue by ashsepra** [macacajs/macaca-datahub#136]
I try to run macaca datahub version 2.4.0 with npm run dev and npm run start. I created datahub, data mock json also with some scenes. I try to check my data mock json locally inside my datahub directory but I cannot find it. May I know where is data mock json store on my local?

**Comment by zivyangll** [comment]
Are you config DataHub data path? If configured, the data is in the directory you configured.

If not, the data in your home directory: ~/.macaca-datahub/

BTW, how to configure DataHub data can refer: https://macacajs.github.io/macaca-datahub/guide/webpack-tutorial.html#how-a-webpack-project-integrates-datahub
```js
const datahubConfig = {
  ...
  store: path.join(__dirname, '..', 'data'),
};
```

**Comment by ashsepra** [comment]
I'm just clone from the latest code on github and try run npm run dev and npm run start
Do I need to try `npm run start:use-config` ?

**Comment by zivyangll** [comment]
@ashsepra 
You can add `datahub.config.js` in your project. Eg: https://github.com/macaca-sample/angular-datahub-sample/blob/master/datahub.config.js
