### ISSUE TITLE
全局安装报错：SQLite3

### ISSUE THREAD

**Issue by dear-lizhihua** [macacajs/macaca-datahub#151]
![image](https://user-images.githubusercontent.com/15142680/69625851-68e74000-1082-11ea-93e0-f6d78097d4cc.png)
安装报错 SQLite3

**Comment by dear-lizhihua** [comment]
项目直接安装没有问题

**Comment by zivyangll** [comment]
@dear-lizhihua 日志里写的比较清楚，创建目录权限不够。npm 装的有些问题吧，可以用 nvm 试试

**Comment by xudafeng** [comment]
SQLITE3_BINARY_SITE=http://npm.taobao.org/mirrors/sqlite3

试试这个mirror呢

**Comment by lk0606** [comment]
> ```
> SQLITE3_BINARY_SITE=http://npm.taobao.org/mirrors/sqlite3
> ```
> 
> 试试这个mirror呢

请问这个镜像据图如何使用呢，

**Comment by lk0606** [comment]
npm i macaca-datahub -D 报错如上，求助

**Comment by xudafeng** [comment]
```bash
$ npm install -g cnpm --registry=https://registry.npm.taobao.org
$ cnpm i macaca-datahub -g
```

cnpm 试试看
