### ISSUE TITLE
代理支持 restful 模式

### ISSUE THREAD

**Issue by zivyangll** [macacajs/macaca-datahub#154]
目前 DataHub 代理只支持网关模式（将请求打到固定地址），@a526672351 希望支持 restful 模式。

**Comment by zhangyuheng** [comment]
路径填写这种试试 `path/:id`
![image](https://user-images.githubusercontent.com/2139038/71154822-6342db80-2277-11ea-826c-0d652d09d90c.png)

**Comment by xudafeng** [comment]
已支持
