### ISSUE TITLE
win10, 启动时（datahub server）报下面的错误

### ISSUE THREAD

**Issue by tkspeking** [macacajs/macaca-datahub#157]
C:\Users\Administrator>datahub server

DataHub start unsuccessfully: Error: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-datahub\node_modules\sequelize-cli\lib\sequelize db:migrate
ERROR: Error reading "database\config.js". Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

Sequelize CLI [Node: 12.14.0, CLI: 5.5.1, ORM: 4.44.3]

**Comment by zivyangll** [comment]
@tkspeking 用 git bash 启动试试
