### ISSUE TITLE
datahub server启动问题

### ISSUE THREAD

**Issue by LuanShiZhiJian** [macacajs/macaca-datahub#158]
DataHub start unsuccessfully: Error: Command failed: D:\nodejs\node_global\node_modules\macaca-datahub\node_modules\_sequelize-cli@5.5.1@sequelize-cli\lib\sequelize db:migrate
ERROR: Error reading "database\config.js". Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

Sequelize CLI [Node: 12.16.1, CLI: 5.5.1, ORM: 4.44.4]

看了下过往类似issure记录，没太明白如何解决？可否具体说明下，谢谢！

**Comment by zivyangll** [comment]
@LuanShiZhiJian 使用 Git Bash 启动试试。

Git Bash：https://gitforwindows.org/

**Comment by LuanShiZhiJian** [comment]
> @LuanShiZhiJian 使用 Git Bash 启动试试。
> 
> Git Bash：https://gitforwindows.org/

@zivyangll 请见如下截图，谢谢！
![image](https://user-images.githubusercontent.com/41558924/76296919-ef522580-62f1-11ea-898a-a3921b7094c5.png)

**Comment by LuanShiZhiJian** [comment]
@zivyangll please advise,thanks
