### ISSUE TITLE
npm run dev问题

### ISSUE THREAD

**Issue by LuanShiZhiJian** [macacajs/macaca-datahub#159]
D:\nodejs\webpack-datahub-sample-master>npm run dev

> webpack-datahub-sample@1.0.0 dev D:\nodejs\webpack-datahub-sample-master
> NODE_ENV=development webpack-dev-server

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-datahub-sample@1.0.0 dev: `NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-datahub-sample@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2020-03-12T02_18_29_336Z-debug.log

如上错误，请给出相关建议，谢谢！

**Comment by zivyangll** [comment]
@LuanShiZhiJian 你用的 win 的命令行工具，不支持怎么写环境变量，用 Git Bash 试试。

**Comment by LuanShiZhiJian** [comment]
> @LuanShiZhiJian 你用的 win 的命令行工具，不支持怎么写环境变量，用 Git Bash 试试。

方便在相关文档中说明下这个问题，以及正确操作说明么？

**Comment by LuanShiZhiJian** [comment]
> @LuanShiZhiJian 你用的 win 的命令行工具，不支持怎么写环境变量，用 Git Bash 试试。

已尝试在git bash执行相同命令，一样的错误结果。
