### ISSUE TITLE
server error: interfaceData.scenes is not iterable

### ISSUE THREAD

**Issue by LuanShiZhiJian** [macacajs/macaca-datahub#160]
上传Swagger格式为json文件，出现如题错误，请建议谢谢！
![image](https://user-images.githubusercontent.com/41558924/76486415-39561b00-645a-11ea-9272-ac2e04980d9c.png)

**Comment by LuanShiZhiJian** [comment]
![image](https://user-images.githubusercontent.com/41558924/76488480-86d58680-6460-11ea-9ed9-3650af91eda6.png)

**Comment by zivyangll** [comment]
@LuanShiZhiJian 方便提供下能复现的 swagger 文件内容么？
