### ISSUE TITLE
使用中的几个问题

### ISSUE THREAD

**Issue by LuanShiZhiJian** [macacajs/macaca-datahub#161]
![image](https://user-images.githubusercontent.com/41558924/76507293-813f6700-6487-11ea-82f9-a3b15dcd113f.png)

1、一个接口下多个场景，我如何写出不同URL来访问多个场景返回结果？
2、请求字段描述，开启校验后，它们是如何校验？预期结果应该什么？

谢谢！

**Comment by zivyangll** [comment]
@LuanShiZhiJian
1. URL 都是一样的，需要手动在 DataHub 平台上切换场景，或者通过 API 切换。可以点击 UI 界面中的 “预览场景数据” 查看。文档中也有写如何使用：https://macacajs.github.io/macaca-datahub/zh/guide/quick-start.html

2. 请求 DataHub 接口的时候，如果开启校验，会检查对应的参数，不对的话，会返回提示信息。

**Comment by LuanShiZhiJian** [comment]
> @LuanShiZhiJian
> 
> 1. URL 都是一样的，需要手动在 DataHub 平台上切换场景，或者通过 API 切换。可以点击 UI 界面中的 “预览场景数据” 查看。文档中也有写如何使用：https://macacajs.github.io/macaca-datahub/zh/guide/quick-start.html
> 2. 请求 DataHub 接口的时候，如果开启校验，会检查对应的参数，不对的话，会返回提示信息。

@zivyangll 
1、我不希望使用手动切换场景。通过API切换是指使用语言SDK来切换吗？比如python\JavaSDK
2、DataHub URL后面添加参数，没有返回结果，是否可以理解正确？
