### ISSUE TITLE
文档疑问

### ISSUE THREAD

**Issue by LuanShiZhiJian** [macacajs/macaca-datahub#162]
![image](https://user-images.githubusercontent.com/41558924/76581462-5ba97080-650e-11ea-8285-c2bb6b0e6040.png)

红框的localhost:8080 是指什么？我不认为他是datahub平台

**Comment by broven** [comment]
.. 你本地的地址啊

**Comment by LuanShiZhiJian** [comment]
> .. 你本地的地址啊

你那边搭的起来么？

**Comment by xudafeng** [comment]
截图是例子，可以根据文档尝试启动
