### ISSUE TITLE
windows兼容问题 startServer方法

### ISSUE THREAD

**Issue by lsh382510118** [macacajs/macaca-datahub#164]
在windows环境下：
   在启动data-hub服务的时候，调用startServer方法：
   `  async startServer() {
    const args = Array.prototype.slice.call(arguments);
    const options = Object.assign(this.options, args[0] || {});

    if (options.database) {
      process.env.DATAHUB_DATABASE = options.database;
    } else if (!options.isCli) {
      const projectDirName = process.cwd()
        .split(path.sep)
        .slice(1)
        .join('_');
      console.log(process.env)
      const databasePath = path.join(process.env.HOME, '.macaca-datahub', projectDirName);
      mkdir(databasePath);
      process.env.DATAHUB_DATABASE = path.join(databasePath, 'macaca-datahub.data');
      console.log(chalk.cyan(`DataHub storage: ${process.env.DATAHUB_DATABASE}`));
    }`
   重点在：
  `const databasePath = path.join(process.env.HOME, '.macaca-datahub', projectDirName);`
把process.env打印出来，并没有“HOME”的属性值

**Comment by lsh382510118** [comment]
修改了2个地方就成功了
1.filePath:node_modules\_macaca-datahub@3.0.3@macaca-datahub\index.js on line -- 40 
`const databasePath = path.join(process.env.HOME, '.macaca-datahub', projectDirName);`
改成
`const databasePath = path.join(process.env.HOME || process.env.HOMEPATH, '.macaca-datahub', projectDirName);`
2.filePath:node_modules\_macaca-datahub@3.0.3@macaca-datahub\database\config.js online -- 6
`const databasePath = path.join(process.env.HOME, '.macaca-datahub');`
改成
`const databasePath = path.join(process.env.HOME || process.env.HOMEPATH, '.macaca-datahub');`

虽然成功了，但是还是有很多不懂，望指正。。。

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-datahub/commit/f0a44dce0629b068c92b78b0e9132e35959baab1
