### ISSUE TITLE
macaca-datahub install error, error in sqlite3

### ISSUE THREAD

**Issue by lk0606** [macacajs/macaca-datahub#169]
![image](https://user-images.githubusercontent.com/43233310/101374790-98619700-38e9-11eb-80b0-1777c78e856c.png)

**Comment by xudafeng** [comment]
```bash
$ nvm use 12 
```

**Comment by lk0606** [comment]
> ```shell
> $ nvm use 12 
> ```
![Uploading image.png…]()
