### ISSUE TITLE
是否考虑新增场景/接口分组便于管理

### ISSUE THREAD

**Issue by likun7981** [macacajs/macaca-datahub#178]
如题

**Comment by zivyangll** [comment]
@likun7981 这个已经在开发中，近期会合并

**Comment by antife-yinyue** [comment]
可以直接提交 PR，反正 DataHub 也是我们自己开源出去的，使用过程中有什么不好用的地方都可以提 PR

**Comment by snapre** [comment]
@likun7981 最新的 Datahub 已经新增了该功能，见 #193 ，可升级到最新版进行体验，体验过程中有任何新的想法或建议都可以提新的 issue。
