### ISSUE TITLE
按照文档操作，一键启动失败

### ISSUE THREAD

**Issue by yulrosy** [macacajs/macaca-datahub#194]
复现步骤：
npm i macaca-datahub -g
datahub server
报错：
DataHub start unsuccessfully: Error: Command failed: /Users/xilan/.nvs/node/14.18.2/x64/lib/node_modules/macaca-datahub/node_modules/sequelize-cli/lib/sequelize db:migrate
ERROR: Cannot find "/Users/xilan/.nvs/node/14.18.2/x64/lib/node_modules/macaca-datahub/config/config.json". Have you run "sequelize init"?
环境：
系统：macOS Big Sur 11.4
Node：v14.18.2
NPM：v6.14.15

**Comment by snapre** [comment]
@yulrosy 问题已解决，可重新安装体验 :)

**Comment by broven** [comment]
same here

**Comment by snapre** [comment]
@broven 报错信息可以提供一下吗

**Comment by broven** [comment]
> @broven 报错信息可以提供一下吗
  https://asciinema.org/a/6xBGZZCQSKIPbb8Sp2nrdyFsd
