### ISSUE TITLE
怎么开启导入导出的功能？

### ISSUE THREAD

**Issue by springxing** [macacajs/macaca-datahub#229]
![image](https://user-images.githubusercontent.com/17450950/178393826-4369c897-c670-48bb-b08c-b670629b63aa.png)

![image](https://user-images.githubusercontent.com/17450950/178393846-bac9219c-a19a-47dd-89ef-924719d2ac04.png)

**Comment by snapre** [comment]
@springxing 
<img width="1439" alt="截屏2022-07-12 13 30 45" src="https://user-images.githubusercontent.com/52845048/178415754-8858d5d2-daf0-4541-a2b6-6847697101d7.png">

<img width="1440" alt="截屏2022-07-12 13 28 33" src="https://user-images.githubusercontent.com/52845048/178415555-f052126f-29ff-42e4-8c3c-86c12ec2272a.png">
