### ISSUE TITLE
[bug] 新增场景后，修改原先场景，发现场景标题错误

### ISSUE THREAD

**Issue by Simplyme0823** [macacajs/macaca-datahub#231]
#### 复现步骤：
1. 创建场景 1；
2. 创建场景 2；
3. 点击场景 1 的编辑按钮，此时，发现其标题为场景 2；

详见下方视频
https://user-images.githubusercontent.com/57203444/183857083-e28ea66f-1811-4f0a-afff-77ddc9dfd061.mp4

#### 期望行为：
无论 v1 场景选中与否，在点击 v1 场景的修改按钮时，弹窗的场景标题都应是 v1 而非 v2。

**Comment by snapre** [comment]
@Simplyme0823 已修复，可升级到最新版本 4.1.7
