### ISSUE TITLE
engines detect not working

### ISSUE THREAD

**Issue by brucejcw** [macacajs/macaca-datahub#29]
node version 8.1.2 also can install macaca-datahub without warning,   
and failed to use `transform-object-rest-spread` feature.  
the macaca-datahub configuration is 
```
"engines": {
    "node": ">=8.9.0"
  },
```
![image](https://user-images.githubusercontent.com/8085088/37649674-186c1dba-2c65-11e8-9697-d62e6f17d6fa.png)

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-datahub/commit/e7ab058b8af7bcf8c6b5e434ef457676df7496fd
