### ISSUE TITLE
Request ，Response弹出框太灵敏了

### ISSUE THREAD

**Issue by xujiewei23** [macacajs/macaca-datahub#35]
稍微一点击在弹出窗外就关闭了，
还有每次键盘之后，都会跳转到最后一个字符后。。

**Comment by zhangyuheng** [comment]
> 还有每次键盘之后，都会跳转到最后一个字符后。。

应该是最近改动出现的 cc @brucejcw 可以看下

**Comment by brucejcw** [comment]
> 还有每次键盘之后，都会跳转到最后一个字符后。。 

@xujiewei23 已修复

关于弹框的问题, 目前的设计统一是弹出窗外就关闭了, 后续可以优化
