### ISSUE TITLE
 datahub server 启动报错了

### ISSUE THREAD

**Issue by NextOneWxf** [macacajs/macaca-datahub#43]
![1](https://user-images.githubusercontent.com/4550421/39105378-113e1e4c-46e8-11e8-959e-7ad64fe20b64.jpg)

**Comment by xudafeng** [comment]
升级Node版本到最新吧

**Comment by NextOneWxf** [comment]
![image](https://user-images.githubusercontent.com/4550421/39163211-11a2d444-47ac-11e8-8d12-13b3925b89bc.png)

**Comment by xudafeng** [comment]
需要升级nodejs版本

**Comment by NextOneWxf** [comment]
大致支持多少版本以上？

**Comment by NextOneWxf** [comment]
已经更新到v9.10.1新的报错信息
![66](https://user-images.githubusercontent.com/4550421/39169306-ea8fe9c8-47c9-11e8-9322-5ab90ca23772.jpg)

**Comment by xudafeng** [comment]
@NextOneWxf

去掉sudo执行，参考 https://github.com/alibaba/macaca/issues/8

重装一次DataHub，或者你可以直接用docker。
