### ISSUE TITLE
datahub支持restful api

### ISSUE THREAD

**Issue by zhuyali** [macacajs/macaca-datahub#44]
现在datahub是以接口名作为key的，但是实际情况下，可能同一个接口名对应不同的http方法，表示不同的含义。比如获取app是get /app，新建app是post /app，更新app是put /app，其实url都一样，只是http方法不同而已

**Comment by xudafeng** [comment]
现在datahub是以接口名作为key的，但是实际情况下，可能同一个接口名对应不同的http方法，表示不同的含义。比如获取app是get /app，新建app是post /app，更新app是put /app，其实url都一样，只是http方法不同而已
