### ISSUE TITLE
DataHub 2.x 升级指南

### ISSUE THREAD

**Issue by zivyangll** [macacajs/macaca-datahub#77]
## 依赖更新

将版本号升级到 2

```js
{
  "macaca-datahub": "2",
  "macaca-wd": "2", // 如果你用到该模块写单元测试，请升级到 2
}
 
```

## 不兼容处理

**⚠️注意: DataHub 2 的底层服务变更，不再兼容 1.x 的数据格式。**

已有的归档数据可以通过如下命令行进行升级：

```plain
$ ./node_modules/.bin/datahub-migrate-1-to-2 -s ./data
```

### 如果你用到 switchScene，请继续阅读

支持 method 属性，具体见 [datahub-nodejs-sdk](https://github.com/macacajs/datahub-nodejs-sdk#common-usage) 文档。

**Comment by zhangyuheng** [comment]
https://github.com/macacajs/macaca-datahub/releases/tag/2.1.9
