### ISSUE TITLE
change sceneName bug(bug)

### ISSUE THREAD

**Issue by zhuyali** [macacajs/macaca-datahub#86]
if i change the currentScene's sceneName, the interface /api/interface get the interface data, and there is a property currentScene remains the older sceneName

**Comment by zhangyuheng** [comment]
Can't only change from dashboard, otherwise it will only affect database and **currentScene** is not exported to json file.

https://github.com/macacajs/macaca-datahub/blob/master/config/config.default.js#L25-L33
