### ISSUE TITLE
代理模式的代理地址期望所有请求共用

### ISSUE THREAD

**Issue by XGHeaven** [macacajs/macaca-datahub#95]
现在的代理模式是一对一的，比如说 `/api/user` 代理到 `example.com/api/user`，这个是没有问题的。

当我开启了全局模式，想实现代理所有请求，比如 `/api/user` `/api/post` `/api/search` ，分别到 `example.com/api/user` `example.com/api/post` `example.com/api/search`，于是我在其中一个接口上添加了一个 `example.com` 的代理，并开启全局模式。我发现所有的请求都打到了 `example.com` 而不是我上面想要的。

我猜测这个全局模式的意思是只是开启了所有的代理，但是每个请求要自己去配置代理的 Endpoint。也就是说代理地址每个请求不共用的。这个在开发的时候其实不太方便，因为后面的时候，几乎所有的接口都是通过代理走的，那么共用一个代理配置其实是比较方便的。我就不需要一个个接口去添加了

上面只是我的理解，以为我也没找到跟代理相关的文档，就使用的结果来说是这个样子的。希望后面能够补齐一下相关的文档。

**Comment by XGHeaven** [comment]
> 如果在前期一次性配置好，后面是不是就会很方便，既可以一键开启关闭，也可以选择性部分开启。

可是现实是一个项目可能有上百个接口，我不可能一开始就把几百个接口的代理都配置好，这也是不现实的。而且我们的这些接口用的自研的一套 api 管理系统，不支持导出。

所以我还是希望能够有一个全局代理的配置，这样我就可以全局开启代理，针对需要 mock 的接口单独配置。

顺便说一句，Datahub 的解决方案我觉得非常好，能解决挺多痛点的，也和我自己的思路很契合，但是现在比较大的问题是功能偏少（我是这么感觉的，也可能我没有使用全面），配置项有点少，可能更多的是针对阿里内部，希望慢慢改进

**Comment by zhangyuheng** [comment]
> 可是现实是一个项目可能有上百个接口，我不可能一开始就把几百个接口的代理都配置好
这种情况需要加全局的

**Comment by XGHeaven** [comment]
@zhangyuheng 现在不是没有全局代理么？只有一键开启全部代理 😂

**Comment by Ma63d** [comment]
+1
全局代理这个需求比较强烈，能否支持呢？
