### ISSUE TITLE
 macaca-datahub server 启动报错

### ISSUE THREAD

**Issue by tailm** [macacajs/macaca-datahub#98]
macaca-datahub server
(node:22126) UnhandledPromiseRejectionWarning: ConnectionTimeoutError: Connect timeout for 3000ms, GET http://registry.cnpmjs.org/macaca-datahub/2 -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Timeout._onTimeout (/usr/local/share/.config/yarn/global/node_modules/urllib/lib/urllib.js:845:15)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:22126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zivyangll** [comment]
@tailm 应该是网络延迟，再试试应该就可以了
