### ISSUE TITLE
datahub网站需求

### ISSUE THREAD

**Issue by rdmclin2** [macacajs/macaca-datahub#99]
1. 项目接口很多 (30+)，可否二级分类?

2. 网站部署上去之后谁都能看，谁都能改不安全，能否加权限控制

**Comment by rdmclin2** [comment]
厉害了，还带自动翻译的

**Comment by rdmclin2** [comment]
Try english

**Comment by zhangyuheng** [comment]
> 项目接口很多 (30+)，可否二级分类?

如果是对接多个服务可以分两开成个 hub 新建多个项目。如果都是对接单个服务，需要改造下界面来支持文件夹分类

> 网站部署上去之后谁都能看，谁都能改不安全，能否加权限控制
计划支持

**Comment by rdmclin2** [comment]
那么再加一个需求: 支持单个接口在项目间的转移

**Comment by rdmclin2** [comment]
还有一个需求:
代理模式，支持正则表达式匹配，全局配置
![image](https://user-images.githubusercontent.com/4705237/47641782-ed2a7380-dba1-11e8-8a0e-670bc1430f06.png)

**Comment by xudafeng** [comment]
@rdmclin2 问题1，能否分多个hub管理？

**Comment by rdmclin2** [comment]
@xudafeng 可以，现有的接口需要迁移，但没有提供接口迁移工具。同时这种方式割裂了项目接口，分散到各个hub中，未来比如有针对项目的全局性配置可能要在多个hub中配置

**Comment by yeyuguo** [comment]
现在想把公司多个项目都走datahub，作为接口的跳转层，因为 datahub 的出现的确可以解决多场景的情况，但有几个需求也是在使用过程中，想要得到的功能类似阿里妈妈的rap2：
* 上述 @rdmclin2 说的，权限控制；
* 参数配置这块，可以做成下拉框形式来选择吗？  
* 是否有计划增加：在代理功能时候，可以填写请求的参数后，再做预览场景；

下面说下为什么不用 rap2，而来这边提需求计划：  
我觉得 datahub 的功能和界面非常的简洁直观，全是100%能用上的功能，非常适合利用做一个所有项目的接口入口层；如果 datahub 能有这个功能的话，不仅仅是开发过程中使用的工具，而可以在生产环境来做很多事。

**Comment by 997282173** [comment]
接口能排序吗

**Comment by snapre** [comment]
@rdmclin2 最新版的 Datahub 已支持项目接口二级分类，可升级到最新版进行体验。
